version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Composer
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"